spring:
  application:
    name: multi-database-demo
  datasource:
    remote:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5434/postgres
      username: postgres
      password: 123456
    local:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 123456
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true